
  //console.log("Content script received: ")
  //console.log(request)
  //console.log(request.paragraph)
  //console.log(request.level)
  //console.log(request.newLevel)
  //console.log(request.index)
  //console.log(request.text)
  //console.log(request.difficultyLevel)
  //console.log(request.simplifiedText)
  //console.log(request.error)
  //console.log(request.data)
  //console.log(request.message)
  //console.log(request.content)
  //console.log(request.text)
  //console.log(request.role)
  //console.log(request.model)
  //console.log(request.answer)
  